### PR TITLE
Improved approach to handle multiple OpenAI providers

### PR DESCRIPTION
**Pull request by sashirestela**

### CODE REVIEW

**Comment by the-gigi** [comment]
@sashirestela thanks for tackling this issue. I started a discussion regarding Gemini support here:
https://github.com/sashirestela/simple-openai/discussions/221

This may inform some decisions you make here (in particular dynamic API key).

**Comment by the-gigi** [comment]
@sashirestela I upgraded our codebase to 3.13.0 with the new approach for OpenAI providers. This PR removed the BaseSimpleOpenAI base class, which supported all the services (trowing unimplemented exceptions for most of them). Now, each provider can implement any subset of the services. This causes a problem if you want to manage multiple providers and operate on them in a polymorphic way.

For example, before the change you could keep a map of model name -> BaseSimpleOpenAI  (the actual instances could be any combination of SimpleOpenAI, SimpleOpenAIAzure and SimpleOpenAIAnyscale) and dynamically choose the BaseSimpleOpenAI instance based on requested model name and call any of its services. Now, it's impossible because the new shared base class OpenAIProvider doesn't support any of the services.

**Comment by sashirestela** [comment]
> which supported all the services (throwing unimplemented exceptions for most of them)

Yeah, that was the point of the modification. I think it is a poor design to have providers that implement only a small subset of services and force users to guess which services are available by checking exceptions or any other registers. Also, I think it is not a good representation of reality: those providers are not interchangeable for all services as a whole, but are at the service level.

So, if you want to work with them in a polymorphic way, you can do it at the service level. For example:

```java
Map<String, Object> providers = new HashMap<>();
providers.put("standard", SimpleOpenAI.builder()
        .apiKey(System.getenv("OPENAI_API_KEY"))
        .organizationId(System.getenv("OPENAI_ORGANIZATION_ID"))
        .build());
providers.put("azure", SimpleOpenAIAzure.builder()
        .apiKey(System.getenv("AZURE_OPENAI_API_KEY"))
        .apiVersion(System.getenv("AZURE_OPENAI_API_VERSION"))
        .baseUrl(System.getenv("AZURE_OPENAI_BASE_URL"))
        .build());
providers.put("anyscale", SimpleOpenAIAnyscale.builder()
        .apiKey(System.getenv("ANYSCALE_API_KEY"))
        .build());
providers.put("mistral", SimpleOpenAIMistral.builder()
        .apiKey(System.getenv("MISTRAL_API_KEY"))
        .build());

ChatCompletionServices chatProvider = (ChatCompletionServices) providers.get("mistral");

var chatResponse = chatProvider.chatCompletions().create(ChatRequest.builder()
        .model("pixtral-12b-2409")
        .message(SystemMessage.of("You are an expert in AI."))
        .message(UserMessage.of("Write a technical article about ChatGPT, no more than 100 words."))
        .temperature(0.0)
        .maxTokens(300)
        .build()).join();

System.out.println(chatResponse.firstContent());
```

**Comment by the-gigi** [comment]
@sashirestela 
> 
> Yeah, that was the point of the modification. I think it is a poor design to have providers that implement only a small subset of services and force users to guess which services are available by checking exceptions or any other registers. 

Yes. I understand the motivation of the change. I'm pointing out a real world situation where the current design with lowest common denominator of the Provider causes users of simple-openai to resort to casting an instance into a particular service whenever they need to make a call to that service. In your example, only the ChatCompletionServices were used. If this is the case then I agree that it is is not much of a bother. I can create a map of model_name -> ChatCompletionServices. But, if I have multiple providers that support several services (e.g. ChatCompletionServices, ImageServices and FilesServices) then I don't a single interface or abstract class that can represent all of them and I have to cast the provider to each type of service before making a call.

Here are some examples from our codebase
```
              () ->
                  ((ChatCompletionServices) instance.openAi())
                      .chatCompletions()
                      .create(request)
                      .get(Duration.ofSeconds(30).toMillis(), TimeUnit.MILLISECONDS));
```

```
    Provider<Future<List<io.github.sashirestela.openai.domain.image.Image>>> makeImageCall =
        () -> ((ImageServices) openAi).images().create(request);
```

It's not a big deal. It's just make the usage a little more cumbersome.

What do you think about the following solution:
- Add a getUniversalProvider() method to OpenAIProvider(). The universal provider will store a reference to the provider. It  will implement all the services. The implementation will be to delegate to the stored provider is it implement the particular service and otherwise throw an unimplemented error.

This way the OpenAIProvider class remains pure. Here is what the UniversalOpenAIProvider can look like:
```
package io.github.sashirestela.openai.base;

import io.github.sashirestela.openai.OpenAI;
import io.github.sashirestela.openai.OpenAIBeta2;
import io.github.sashirestela.openai.OpenAIRealtime;
import io.github.sashirestela.openai.service.AssistantServices;
import io.github.sashirestela.openai.service.AudioServices;
import io.github.sashirestela.openai.service.BatchServices;
import io.github.sashirestela.openai.service.ChatCompletionServices;
import io.github.sashirestela.openai.service.CompletionServices;
import io.github.sashirestela.openai.service.EmbeddingServices;
import io.github.sashirestela.openai.service.FileServices;
import io.github.sashirestela.openai.service.FineTunningServices;
import io.github.sashirestela.openai.service.ImageServices;
import io.github.sashirestela.openai.service.ModelServices;
import io.github.sashirestela.openai.service.ModerationServices;
import io.github.sashirestela.openai.service.RealtimeServices;
import io.github.sashirestela.openai.service.SessionServices;
import io.github.sashirestela.openai.service.UploadServices;

/**
 * This class wraps an OpenAI provider and exposes all the services
 *
 * It delegates to the wrapped provider if it implements a particular service and otherwise
 * raises an unimplemented exception.
 */
public class OpenAIUniversalProvider implements
    AssistantServices,
    AudioServices,
    BatchServices,
    ChatCompletionServices,
    CompletionServices,
    EmbeddingServices,
    FileServices,
    FineTunningServices,
    ImageServices,
    ModelServices,
    ModerationServices,
    RealtimeServices,
    SessionServices,
    UploadServices {
    private OpenAIProvider provider;

    public OpenAIUniversalProvider(OpenAIProvider provider) {
        this.provider = provider;
    }

    @Override
    public OpenAI.Audios audios() {
        if (provider instanceof AudioServices) {
            return ((AudioServices) provider).audios();
        }
        throw new UnsupportedOperationException("audios");
    }

    @Override
    public OpenAI.Batches batches() {
        if (provider instanceof BatchServices) {
            return ((BatchServices) provider).batches();
        }
        throw new UnsupportedOperationException("batches");
    }

    @Override
    public OpenAI.ChatCompletions chatCompletions() {
        if (provider instanceof ChatCompletionServices) {
            return ((ChatCompletionServices) provider).chatCompletions();
        }
        throw new UnsupportedOperationException("chatCompletions");
    }

    @Override
    public OpenAI.Completions completions() {
        return getOrCreateService(OpenAI.Completions.class);
    }

    @Override
    public OpenAI.Embeddings embeddings() {
        return getOrCreateService(OpenAI.Embeddings.class);
    }

    @Override
    public OpenAI.Files files() {
        return getOrCreateService(OpenAI.Files.class);
    }

    @Override
    public OpenAI.FineTunings fineTunings() {
        return getOrCreateService(OpenAI.FineTunings.class);
    }

    @Override
    public OpenAI.Images images() {
        return getOrCreateService(OpenAI.Images.class);
    }

    @Override
    public OpenAI.Models models() {
        return getOrCreateService(OpenAI.Models.class);
    }

    @Override
    public OpenAI.Moderations moderations() {
        return getOrCreateService(OpenAI.Moderations.class);
    }

    @Override
    public OpenAI.Uploads uploads() {
        return getOrCreateService(OpenAI.Uploads.class);
    }

    @Override
    public OpenAI.SessionTokens sessionTokens() {
        return getOrCreateService(OpenAI.SessionTokens.class);
    }

    @Override
    public OpenAIBeta2.Assistants assistants() {
        return getOrCreateService(OpenAIBeta2.Assistants.class);
    }

    @Override
    public OpenAIBeta2.Threads threads() {
        return getOrCreateService(OpenAIBeta2.Threads.class);
    }

    @Override
    public OpenAIBeta2.ThreadMessages threadMessages() {
        return getOrCreateService(OpenAIBeta2.ThreadMessages.class);
    }

    @Override
    public OpenAIBeta2.ThreadRuns threadRuns() {
        return getOrCreateService(OpenAIBeta2.ThreadRuns.class);
    }

    @Override
    public OpenAIBeta2.ThreadRunSteps threadRunSteps() {
        return getOrCreateService(OpenAIBeta2.ThreadRunSteps.class);
    }

    @Override
    public OpenAIBeta2.VectorStores vectorStores() {
        return getOrCreateService(OpenAIBeta2.VectorStores.class);
    }

    @Override
    public OpenAIBeta2.VectorStoreFiles vectorStoreFiles() {
        return getOrCreateService(OpenAIBeta2.VectorStoreFiles.class);
    }

    @Override
    public OpenAIBeta2.VectorStoreFileBatches vectorStoreFileBatches() {
        return getOrCreateService(OpenAIBeta2.VectorStoreFileBatches.class);
    }

    @Override
    public OpenAIRealtime realtime() {
        return this.realtime;
    }
    .
    .
    .
}
```

Then, we just need to add this method to OpenAIProvider:

```
    public OpenAIUniversalProvider getUniversalProvider() {
        return new OpenAIUniversalProvider(this);
    }
```

Now, users can manage a map of model_name -> UniversalOpenAIProvider. It's their responsibility to to store providers that have a shared set of services and call only services that are available by all providers (or deal with unsupported services by catching the exception).

**Comment by sashirestela** [comment]
@the-gigi I think I've mentioned this before, providers cannot be treated as interchangeable, they only implement a small subset of the standard services. Simple-OpenAI aims to reflect that reality with a clean and elegant codebase.

Your proposal to handle a multi-provider/multi-service scenario is very similar to the old code I've refactored and is not aligned with Simple-OpenAI principles, so it will not be part of this codebase.

If you think it's a valuable scenario, you should implement it in your own codebase, but I suggest you don't use unimplemented methods, there are more appropriate approaches: direct interface implementations, factory pattern, strategy pattern, composition over inheritance, service locator pattern, but all of them should be applied for specific cases and cannot be generalized for all services (for this reason it cannot be part of the library).

**Comment by the-gigi** [comment]
@sashirestela I agree that  providers in general re not interchangable in respect to the entire OpenAI API. This modeled correctly in the design of simple-openai. The universal provider I suggest is intended to be used as a building block for a set of providers that are interchangable for a subset of the OpenAI API (e.g. chat completion + images + models). I can create such custom class that wraps a universal provider and expose only the interfaces supported by all the concrete providers.

I can do the same thing by wrapping the vanilla OpenAIProvider too, but then I'll have to explicitly cast the OpenAIProvider to the target service before making any call.

Anyway, I respect your opinion and I understand you see it differently, so no need to discuss it anymore.

**Pull request merged**
