### PR TITLE
Fixes for issues with SonarCloud after merging Azure changes

### PR DESCRIPTION
**Pull request by the-gigi**
- Create BaseChatServiceDemo
- Create BaseAssistantServiceDemo
- Move all duplicate logic from provider specific demos to base classes
- Unified the call chat with image functionality into a single method 
- Get rid of workaround by moving annotation to method level

### CODE REVIEW

**Comment by sashirestela** [comment]
@the-gigi This PR is only to fix the issues raised after your PR for Azure changes, please focus this new PR to the Issue https://github.com/sashirestela/simple-openai/issues/90, don't make other changes. Please, revert changes to Demo code.

**Review by sashirestela — CHANGES_REQUESTED** [review]
Please, revert changes to Demo code, the issue related to this PR is just to fix the issues raised for your Azure changes.

In addition, there are two minor observations.

**Review by sashirestela — APPROVED** [review]

**Comment by sashirestela** [comment]
@the-gigi SonarCloud's quality metrics have worsened after merging this PR. I don't know why SonarCloud hasn't caught all the code smells and duplicate code. I think that the feature to support other vendors needs an overall refactor. Please, don't make more contributions until more news.

**Comment by the-gigi** [comment]
> @the-gigi SonarCloud's quality metrics have worsened after merging this PR. I don't know why SonarCloud hasn't caught all the code smells and duplicate code. I think that the feature to support other vendors needs an overall refactor. Please, don't make more contributions until more news.
> 
> @the-gigi I'm afraid that you are not following the Contributions guide, because if you would have used the SonarLint locally, you could have detected all the quality issues:
>

I don't want to install SonarLint locally. I have too many plugins in my IDE already and it's causing issues. I was going based on the PR comment of SonarCloud, which show 0 issues and the quality gate passed. I'm not sure why there is a discrepancy. If there is a CLI-based tool I'll be happy to use that.

**Pull request merged**
