### PR TITLE
Added support for file_search/ranking_options and results responses, additional error states

### PR DESCRIPTION
**Pull request by amavashev**
Added support for file_search/ranking_options and file_search/results responses, additional error states.
As per: https://platform.openai.com/docs/api-reference/run-steps/step-object

### CODE REVIEW

**Comment by sashirestela** [comment]
@amavashev Thanks for using simple-openai and for being proactive to contribute to this project. I would like to suggest some points before creating a PR:

- Create a PR after some minimal discussion to be on the same page.
- Follow all the steps in the [Contributing guideline](https://github.com/sashirestela/simple-openai/blob/main/CONTRIBUTING.md). Though Configure IDE is optional, it is very helpful.
- If you create a PR, don't change the project version.

That said, I'm working on this topic and considering some related stuff, so I think you are duplicating efforts.

Best regards

**Comment by amavashev** [comment]
Ok, will do.

**Comment by sashirestela** [comment]
@amavashev Before you close your PR, I would like to know where you find these additional values? I ask you because in the [OpenAI technical documentation](https://github.com/openai/openai-openapi/blob/master/openapi.yaml#L14628-L14644) (which has been updated two days ago) I can't find your "invalid_image" option:

image

**Comment by amavashev** [comment]
> @amavashev Before you close your PR, I would like to know where you find these additional values? I ask you because in the [OpenAI technical documentation](https://github.com/openai/openai-openapi/blob/master/openapi.yaml#L14628-L14644) (which has been updated two days ago) I can't find your "invalid_image" option:
> 
> image

We see these during actual runtime. had to add these additional error codes to avoid JSON serialization errors.

**Comment by sashirestela** [comment]
@amavashev I'm afraid that I haven't been clear enough with my previous messages. What I meant is that you have to stop working on this PR because I'm already working on implementing the full new functionality (https://github.com/sashirestela/simple-openai/issues/182). My suggestions were for next contributions. Sorry for any confusion.

**Comment by amavashev** [comment]
Ok I am not working on this PR. I can close it.

**Pull request closed without merging**
